default: hot-reload

hot-reload:
        cargo watch -q -c -w src -w Cargo.toml -x 'run -- -vv'

clippy-watch:
        cargo watch -q -c -w src -w Cargo.toml -x clippy

test-watch:
        cargo watch -q -c -w src -w Cargo.toml -x test
